/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF(
    "/models/Artics.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        name='Sounds'
        castShadow
        receiveShadow
        geometry={nodes.Sounds.geometry}
        material={materials.Orange_Plastic}
      />
      <mesh
        name='Cylinders'
        castShadow
        receiveShadow
        geometry={nodes.Cylinders.geometry}
        material={materials.ArticsMaterial}
      />
      <mesh
        name='Pads'
        castShadow
        receiveShadow
        geometry={nodes.Pads.geometry}
        material={materials.ArticsMaterial}
      />
      <mesh
        name='Supports'
        castShadow
        receiveShadow
        geometry={nodes.Supports.geometry}
        material={materials.ArticsMaterial}
      />
      <mesh
        name='Covers'
        castShadow
        receiveShadow
        geometry={nodes.Covers.geometry}
        material={materials.ArticsMaterial}
      />
      <mesh
        name='Inside_1'
        castShadow
        receiveShadow
        geometry={nodes.Inside_1.geometry}
        material={materials.ArticsMaterial}
        position={[0.01, 0, 0]}
      />
      <mesh
        name='Inside_2'
        castShadow
        receiveShadow
        geometry={nodes.Inside_2.geometry}
        material={materials.ArticsMaterial}
        position={[0.01, 0, 0]}
      />
      <mesh
        name='Battery_Holder'
        castShadow
        receiveShadow
        geometry={nodes.Battery_Holder.geometry}
        material={materials.ArticsMaterial}
        position={[0, 0.01, 0]}
      />
      <mesh
        name='InnerTaps'
        castShadow
        receiveShadow
        geometry={nodes.InnerTaps.geometry}
        material={materials.ArticsMaterial}
        position={[0, 0.01, 0]}
      />
      <mesh
        name='Headband_Inner'
        castShadow
        receiveShadow
        geometry={nodes.Headband_Inner.geometry}
        material={materials.BakedArticsMaterial}
      />
      <mesh
        name='Circle074'
        castShadow
        receiveShadow
        geometry={nodes.Circle074.geometry}
        material={materials.BakedArticsMaterial}
      />
      <mesh
        name='Circle074_1'
        castShadow
        receiveShadow
        geometry={nodes.Circle074_1.geometry}
        material={materials.ArticsMaterial}
      />
      <mesh
        name='Brand'
        castShadow
        receiveShadow
        geometry={nodes.Brand.geometry}
        material={materials.BakedArticsMaterial}
      />
    </group>
  );
}

useGLTF.preload("/models/Artics.glb");
